MyTravelCMS/Models/Tip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyTravelCMS.Models
{
    public class Tip
    {
        [Key, ScaffoldColumn(false)]
        public int TipID { get; set; }

        [Required, StringLength(255), Display(Name = "Title")]
        public string TipTitle { get; set; }

        [StringLength(int.MaxValue), Display(Name = "Content")]
        public string TipContent { get; set; }

        public int HasImg { get; set; }
        public string ImgType { get; set; }


        public virtual Country Country { get; set; }
        public virtual Traveller Traveller { get; set; }
    }
}

MyTravelCMS/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTravelCMS.Models;
using System.Data.SqlClient;

namespace MyTravelCMS.Controllers
{
    public class CountryController : Controller
    {
        private TravelCMSContext db = new TravelCMSContext();

        // GET: Country
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult New()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(string countryName)
        {
            string query = "insert into Countries (CountryName) " +
                "values (@name)";

            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@name", countryName);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

        public ActionResult Details(int id)
        {
            return View(db.Countries.Find(id));
        }

        public ActionResult Delete(int id)
        {
            //delete tips associated with the deleted country
           string query = "delete from tips where Country_CountryID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            //delete the country
            query = "delete from countries where CountryID = @id";
            param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
        
            return RedirectToAction("List");

        }

        public ActionResult List()
        {
            return View(db.Countries.ToList());
        }
    }
}
//the code may contain adopted and modified parts from inclass example as well as from online source https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments

MyTravelCMS/Controllers/TipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTravelCMS.Models;
using MyTravelCMS.Models.ViewModels;
using System.IO;

namespace MyTravelCMS.Controllers
{
    public class TipController : Controller
    {
        private TravelCMSContext db = new TravelCMSContext();
        // GET: Tip
        public ActionResult Index()
        { //make List in view
            return RedirectToAction("List");         
        }

        public ActionResult New()
        {
            TipEdit tipEditView = new TipEdit();
            tipEditView.Countries = db.Countries.ToList();
            tipEditView.Travellers = db.Travellers.ToList();

            return View(tipEditView);
        }

        [HttpPost]
        public ActionResult Create(string TipTitle_New, string TipContent_New, int TipTraveller_New, int? TipCountry_New)
        {
            string query = "insert into Tips (TipTitle, TipContent, HasImg, ImgType, Country_CountryID, Traveller_TravellerID ) " +
                "values (@title,@content, 0, 0, @cid, @tid)";

            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@title", TipTitle_New);
            myparams[1] = new SqlParameter("@content", TipContent_New);
            myparams[2] = new SqlParameter("@cid", TipCountry_New);
            myparams[3] = new SqlParameter("@tid", TipTraveller_New);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

        public ActionResult Details(int id)
        {//don't forget to make Details in view
            string query = "select * from tips where tipid =@id";

            return View(db.Tips.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Edit(int? id)
        {
            //compound view         
            TipEdit tipEdit = new TipEdit();
            tipEdit.Tip = db.Tips.Find(id);
            tipEdit.Countries = db.Countries.ToList();
            tipEdit.Travellers = db.Travellers.ToList();
            if (tipEdit.Tip != null) return View(tipEdit);
            else return HttpNotFound();
        }
        //edit
        [HttpPost]
        public ActionResult Edit(int? id, string TipTitle, string TipContent, int? TipCountry, int? TipTraveller, HttpPostedFileBase tipImg)
        {
            if (tipImg != null || tipImg?.ContentLength > 0)
            {
                //this part adopted from inclass example 
                //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(tipImg.FileName).Substring(1);

                if (valtypes.Contains(extension))
                {
                    string imgStr = id + "." + extension;

                    string path = Path.Combine(Server.MapPath("~/images/UploadedFiles"), imgStr);

                    tipImg.SaveAs(path);

                    int HasImg = 1;
                    string ImgType = extension;

                    string pictureQuery = "update tips set HasImg=@hasImg, ImgType=@type where tipid=@id";
                    SqlParameter[] picParams = new SqlParameter[3];
                    picParams[0] = new SqlParameter("@hasImg", HasImg);
                    picParams[1] = new SqlParameter("@type", ImgType);
                    picParams[2] = new SqlParameter("@id", id);

                    db.Database.ExecuteSqlCommand(pictureQuery, picParams);

                }
            }



            if ((id == null) || (db.Tips.Find(id) == null))
            {
                return HttpNotFound();

            }
          
            string query = "update tips set tiptitle=@title, " +
                "tipcontent=@content, " +
                "Country_CountryID=@cid, " + "Traveller_TravellerID=@tid where tipid = @id";
            SqlParameter[] parameters = new SqlParameter[5];
            
            parameters[0] = new SqlParameter("@title", TipTitle);
            parameters[1] = new SqlParameter("@content", TipContent);
            parameters[2] = new SqlParameter("@cid", TipCountry);
            parameters[3] = new SqlParameter("@tid", TipTraveller);
            parameters[4] = new SqlParameter("@id", id);

            
            
            db.Database.ExecuteSqlCommand(query, parameters);


            return RedirectToAction("Details/" + id);
        }
    
        public ActionResult Delete(int id)
        {
            string query = "delete from tips where TipID = @id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
             
            return RedirectToAction("List");

        }

        public ActionResult List()
        { 
            return View(db.Tips.ToList());
        }
    }
}
//the code contains adopted and modified parts from inclass example as well as from online source https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments

MyTravelCMS/Controllers/TravellerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTravelCMS.Models;
using System.Data.SqlClient;

namespace MyTravelCMS.Controllers
{
    public class TravellerController : Controller
    {
        private TravelCMSContext db = new TravelCMSContext();

        // GET: Traveller
        public ActionResult Index()
        {
            return RedirectToAction("List");
            //make List in view
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string travellerName, string travellerBio)
        {
            string query = "insert into Travellers (TravellerName, TravellerBio) " +
                "values (@name,@bio)";

            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", travellerName);
            myparams[1] = new SqlParameter("@bio", travellerBio);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            return View(db.Travellers.Find(id));
        }

        [HttpPost]
        public ActionResult Edit(int? id, string travellerName, string travellerBio)
        {
            if ((id == null) || (db.Travellers.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "update travellers set TravellerName=@name, TravellerBio=@bio where travellerid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name", travellerName);
            myparams[1] = new SqlParameter("@bio", travellerBio);
            myparams[2] = new SqlParameter("@id", id);

             db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");

        }

        public ActionResult Details(int id)
        {
            return View(db.Travellers.Find(id));
        }

        public ActionResult Delete(int id)
        {
            string query = "delete from travellers where TravellerID = @id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            
            return RedirectToAction("List");

        }

        public ActionResult List()
        {
           
            return View(db.Travellers.ToList());

        }
    }
}
//the code may contain adopted and modified parts from inclass example as well as from online source https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments

MyTravelCMS/Views/Tip/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

MyTravelCMS/Views/Tip/Details.cshtml
@model MyTravelCMS.Models.Tip
@{
    ViewBag.Title = "Details";
}

<h2 style="font-family: 'Pacifico', cursive;">@Model.TipTitle</h2>

<div class="btn btn-default pull-right">
    @Html.ActionLink("Edit", "Edit/" + Model.TipID)
</div>
<div class="btn btn-default pull-right">
    @Html.ActionLink("Delete", "Delete/" + Model.TipID)
</div>
<div>
    <div>
        <span>
            Country: @Html.ActionLink(Model.Country.CountryName, "Details/" + Model.Country.CountryID, "Country")
        </span>
    </div>
    <div>
        <span>
            By: @Html.ActionLink(Model.Traveller.TravellerName, "Details/" + Model.Traveller.TravellerID, "Traveller")
        </span>
    </div>
    <div class="image">
        @if (Model.HasImg == 1)
        {
            <div class="image">
                <img src="~/images/UploadedFiles/@(Model.TipID).@(Model.ImgType)" />
            </div>
        }
        
    </div>

    <div class="showlist" style="margin:0 auto; width:950px;">
        <br />
        <p>@Model.TipContent</p>
    </div>
</div>

MyTravelCMS/Views/Tip/Edit.cshtml
@model MyTravelCMS.Models.ViewModels.TipEdit
    @{
        ViewBag.Title = "Edit";
    }

    <h2>Edit "@Model.Tip.TipTitle"</h2>

    <form method="POST" action="/Tip/Edit/@Model.Tip.TipID" enctype="multipart/form-data">
        <div class="form-group">
            <label>Title:</label>
            <input type="text" value="@Model.Tip.TipTitle" id="TipTitle" name="TipTitle" class="form-control" />
        </div>
        <div class="form-group">
            <label>Country:</label>
            <select id="TipCountry" name="TipCountry" class="form-control">
                @foreach (var country in Model.Countries)
                {
                    string current = "";
                    if (country.CountryID == Model.Tip.Country.CountryID)
                    {
                        current = "selected";
                    }

                    <option value="@country.CountryID" @current>@country.CountryName</option>
                }

            </select>
        </div>
        <div class="form-group">
            <label>Traveller:</label>
            <select id="TipTraveller" name="TipTraveller" class="form-control">
                @foreach (var traveller in Model.Travellers)
                {
                    string current = "";
                    if (traveller.TravellerID == Model.Tip.Traveller.TravellerID)
                    {
                        current = "selected";
                    }

                    <option value="@traveller.TravellerID" @current>@traveller.TravellerName</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label>Content:</label>
            <textarea id="TipContent" name="TipContent" class="form-control">@Model.Tip.TipContent</textarea>
        </div>

        <div class="form-group">
            <label>Image:</label>

            <div class="img-container">
                <img src="~/images/UploadedFiles" />
            </div>
        </div>
        <div class="form-group">
            <label>Upload Image:</label>

            <input type="file" name="tipImg" id="tipImg" />

        </div>

        <div>
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </form>

MyTravelCMS/Views/Tip/List.cshtml
@model IEnumerable<MyTravelCMS.Models.Tip>
@{


    ViewBag.Title = "List";
}
<h2>List of Tips</h2>
<div class="btn btn-default pull-right">
    @Html.ActionLink("Give a New Tip", "New")
</div>
<div>
    @foreach (var Tip in Model)
    {

        <div class="showlist" style="font-family: 'Open Sans', sans-serif;">         
               @Html.ActionLink(Tip.TipTitle, "Details/" + Tip.TipID)
        </div>

    }
</div>

MyTravelCMS/Views/Tip/New.cshtml
@model MyTravelCMS.Models.ViewModels.TipEdit
@{
    ViewBag.Title = "New";
}

<h2>New Tip</h2>
<form method="POST" action="/Tip/Create">
    <div class="form-group">
        <label>Title:</label>
        <input id="TipTitle_New" name="TipTitle_New" class="form-control" />
    </div>
    <div class="form-group">
        <label>Country:</label>
        <select id="TipCountry_New" name="TipCountry_New" class="form-control">
            @foreach (var country in Model.Countries)
            {
                <option value="@country.CountryID">@country.CountryName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Traveller:</label>
        <select id="TipTraveller_New" name="TipTraveller_New" class="form-control">
            @foreach (var traveller in Model.Travellers)
            {
                <option value="@traveller.TravellerID">@traveller.TravellerName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Content:</label>
        <textarea id="TipContent_New" name="TipContent_New" class="form-control"></textarea>
    </div>
    <div>
        <input type="submit" value="Submit" class="btn btn-default" />
    </div>
</form>